services:
  server:
    build:
      context: .
    environment:
      NODE_ENV: production
      DB_HOST: 127.0.0.1 # <====================>
      DB_PORT: 3306      # to connect to local DB
    network_mode: "host" # <====================>
    ports:
      - 1337:1337