services:
  server:
    build:
      context: .
    dockerfile: $DOCKERFILE
    environment:
      NODE_ENV: production
    network_mode: "host" # to connect to local DB
    ports:
      - $PORT:$PORT